# Categorized signals based on which core scripts write them to OpenPLC
# Generated from signals.py and core script analysis
# Only includes signals written via modbus_client.write_signal(signal_name)

categorized_signals = {
    "bagger.py": ['bagger', 'bagging'],
    "box_maker.py" : ['box_maker', 'boxing'],
    "conveyor.py": ['conveyor', 'conveyor_fpm'],
    "conveyor_1.py": ['conveyor_1', 'conveying_1'],
    "conveyor_2.py": ['conveyor_2', 'conveying_2'],
    "conveyor_3.py": ['conveyor_3', 'conveying_3'],
    "conveyor_4.py": ['conveyor_4', 'conveying_4'],
    "conveyor_5.py": ['conveyor_5', 'conveying_5'],
    "diverter_valve.py": ['dv'],
    "exhaust_fan.py": ['exhaust_fan'],
    "fan_1.py": ['fan_1'],
    "fan_2.py": ['fan_2'],
    "fan_3.py": ['fan_3'],
    "flour_silo.py": ['lcf_1', 'lcf_2', 'lcf_3', 'lcf_4'],
    "flour_valve.py": ['rv_1'],
    "hopper_valve.py": ['rv_3'],
    "hopper.py" : ['lch'],
    "mixer.py": ['mixer', 'mixer_rpm', 'lcm'],
    "nitrogen_tank.py" : ['nitrogen_volume'],
    "nitrogen_valve.py": ['gv_1'],
    "palletizer.py": ['palletizer', 'palletizer_grabbing', 'palletizer_moving', 'palletizer_target_rotation'],
    "papercutter.py": ['paper_cutter', 'papercut_cpm'],
    "ps_1": ['ps_1'],
    "ps_2": ['ps_2'],
    "ps_3": ['ps_3'],
    "ps_4": ['ps_4'],
    "ps_5": ['ps_5'],
    "ps_6": ['ps_6'],
    "simulated.py": ['trough_transfer', 'add_ingredients', 'reset'],
    "sugar_silo.py": ['lcs_1', 'lcs_2', 'lcs_3', 'lcs_4'],
    "sugar_valve.py": ['rv_2'],
    "taper.py": ['taper', 'taping'],
    "temp_sensor.py": ['tunnel_temp'],
    "trough.py": ['trough_weight'],
    "vacuum.py": ['vacuum', 'vacuum_manual', 'vacuum_rpm'],
    "wirecutter.py": ['wirecutter', 'wirecut_cpm'],
    "wrapper.py": ['wrapper', 'wrapping', 'wrapper_conveying'],
    "roe_1.py" : ['roe_1'],
    "roe_2.py" : ['roe_2'],
    "roe_3.py" : ['roe_3'],
    "worker_present.py" : ['worker_present']
}