x-factory-service: &factory-service
  build:
    context: ..
    target: factory
  restart: always
  environment:
    - PYTHONUNBUFFERED=1
  depends_on:
    - redis_server
  networks:
    factory_net: {}

networks:
  factory_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  redis_server:
    build:
      context: ..
      target: redis
    restart: always
    environment:
    - PYTHONUNBUFFERED=1
    command: python /app/utils/redis_server.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.100

  attacker:
    image: metasploitframework/metasploit-framework
    restart: always
    networks:
      factory_net:
        ipv4_address: 172.30.0.250
    stdin_open: true
    tty: true

  bagger:
    <<: *factory-service
    command: python /app/core/bagger.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.10

  box_maker:
    <<: *factory-service
    command: python /app/core/box_maker.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.11

  conveyor_1:
    <<: *factory-service
    command: python /app/core/conveyor_1.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.12

  conveyor_2:
    <<: *factory-service
    command: python /app/core/conveyor_2.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.13

  conveyor_3:
    <<: *factory-service
    command: python /app/core/conveyor_3.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.14

  conveyor_4:
    <<: *factory-service
    command: python /app/core/conveyor_4.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.15

  conveyor_5:
    <<: *factory-service
    command: python /app/core/conveyor_5.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.16

  conveyor:
    <<: *factory-service
    command: python /app/core/conveyor.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.17

  diverter_valve:
    <<: *factory-service
    command: python /app/core/diverter_valve.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.18

  exhaust_fan:
    <<: *factory-service
    command: python /app/core/exhaust_fan.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.19

  fan_1:
    <<: *factory-service
    command: python /app/core/fan_1.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.20

  fan_2:
    <<: *factory-service
    command: python /app/core/fan_2.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.21

  fan_3:
    <<: *factory-service
    command: python /app/core/fan_3.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.22

  flour_silo:
    <<: *factory-service
    command: python /app/core/flour_silo.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.23

  flour_valve:
    <<: *factory-service
    command: python /app/core/flour_valve.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.24

  hopper_valve:
    <<: *factory-service
    command: python /app/core/hopper_valve.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.25

  hopper:
    <<: *factory-service
    command: python /app/core/hopper.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.26

  mixer:
    <<: *factory-service
    command: python /app/core/mixer.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.27

  nitrogen_tank:
    <<: *factory-service
    command: python /app/core/nitrogen_tank.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.28

  nitrogen_valve:
    <<: *factory-service
    command: python /app/core/nitrogen_valve.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.29

  palletizer:
    <<: *factory-service
    command: python /app/core/palletizer.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.30

  papercutter:
    <<: *factory-service
    command: python /app/core/papercutter.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.31

  ps_1:
    <<: *factory-service
    command: python /app/core/ps_1.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.32

  ps_2:
    <<: *factory-service
    command: python /app/core/ps_2.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.33

  ps_3:
    <<: *factory-service
    command: python /app/core/ps_3.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.34

  ps_4:
    <<: *factory-service
    command: python /app/core/ps_4.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.35

  ps_5:
    <<: *factory-service
    command: python /app/core/ps_5.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.36

  ps_6:
    <<: *factory-service
    command: python /app/core/ps_6.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.37

  simulated:
    <<: *factory-service
    command: python /app/core/simulated.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.38

  sugar_silo:
    <<: *factory-service
    command: python /app/core/sugar_silo.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.39

  sugar_valve:
    <<: *factory-service
    command: python /app/core/sugar_valve.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.40

  taper:
    <<: *factory-service
    command: python /app/core/taper.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.41

  temp_sensor:
    <<: *factory-service
    command: python /app/core/temp_sensor.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.42

  trough:
    <<: *factory-service
    command: python /app/core/trough.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.43

  vacuum:
    <<: *factory-service
    command: python /app/core/vacuum.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.44

  wirecutter:
    <<: *factory-service
    command: python /app/core/wirecutter.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.45

  wrapper:
    <<: *factory-service
    command: python /app/core/wrapper.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.46
  
  roe_1:
    <<: *factory-service
    command: python /app/core/roe_1.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.47
  
  roe_2:
    <<: *factory-service
    command: python /app/core/roe_2.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.48
  
  roe_3:
    <<: *factory-service
    command: python /app/core/roe_3.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.49
  
  worker_present:
    <<: *factory-service
    command: python /app/core/worker_present.py
    networks:
      factory_net:
        ipv4_address: 172.30.0.50